# Generated by Django 5.2.12 on 2026-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BallonMass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen', models.IntegerField()),
                ('argon', models.IntegerField()),
                ('nitrogen', models.IntegerField()),
            ],
        ),
    ]
